name: CI/CD GreenCity

on:
  push:
    branches:
      - main
      - master
      - dev_java21

  pull_request:
    branches:
      - main
      - master
      - dev_java21
      - my_dev_java21

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'oracle'  # 'temurin'
  SETUP_JAVA_CACHE: 'maven'

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11     # v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93   # v4.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.SETUP_JAVA_CACHE }}

      - name: Build a JAR package via Maven

        run: mvn --batch-mode --no-transfer-progress -DskipTests clean package && ls -la

      - name: Run Unit Tests via Maven
        run: mvn --batch-mode --no-transfer-progress clean test

      - name: Upload JUnit Test Report as Artifact
        uses: actions/upload-artifact@v4   # v4.3.1
        if: success() || failure()
        with:
          name: JUnit Test Report
          path: |
            core/target/surefire-reports/*.xml
            service/target/surefire-reports/*.xml
            service-api/target/surefire-reports/*.xml

      - name: Publish JUnit Test Report
        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8   # v1.8.0
        if: success() || failure()
        with:
          name: JUnit Test Report
          path: |
            core/target/surefire-reports/*.xml
            service/target/surefire-reports/*.xml
            service-api/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true