name: CI/CD GreenCity

on:
  push:
    branches:
      - main
      - master
      - dev_java21

  pull_request:
    branches:
      - main
      - master
      - dev_java21
      - my_dev_java21

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'oracle'  # 'temurin'
  SETUP_JAVA_CACHE: 'maven'

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11     # v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93   # v4.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.SETUP_JAVA_CACHE }}

      - name: Build a JAR package via Maven
        run: mvn --batch-mode --no-transfer-progress -DskipTests clean package && la -la
        
      - name: Upload JAR artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: my-jar
          path: ./*.jar